export const speciesData = [
  {
    Name: "Hawksbill Turtle (Eretmochelys imbricata)",
    EndangeredType: "Critically Endangered",
    Weight: "41-68 kilograms",
    Height: "61 to 107 centimeters",
    LifeSpan: "50 to 60 years",
    NumberLeft: "8,000 turtles (from which 1,000 females)",
    EndangeredSince: "1970",
    Region: "West Atlantic (Caribbean), Indian, and Indo-Pacific Oceans",
    img: "image-01.jpg",
    id: "001",
  },
  {
    Name: "Vaquita (Phoeocna sinus)",
    EndangeredType: "Critically Endangered",
    Weight: "~54 kilograms",
    Height: "~150 centimeters",
    LifeSpan: "At least 21 years",
    NumberLeft: "~10 vaquitas",
    EndangeredSince: "1985",
    Region: "The Northern Part of the Gulf of California in Mexico",
    img: "image-01.jpg",
    id: "002",
  },
  {
    Name: "Blue Whale (Balaenoptera musculus)",
    EndangeredType: "Endangered",
    Weight: "Up to 200 tons",
    Height: "20 to 25 meters",
    NumberLeft: "10,000 to 25,000 Blue whales",
    LifeSpan: "Around 80 to 90 years",
    EndangeredSince: "1970",
    Region: "All Oceans Except the Arctic",
    img: "image-01.jpg",
    id: "003",
  },
  {
    Name: "Kemp’s Ridley Sea Turtle (Lepidochelys kempii)",
    EndangeredType: "Endangered",
    Weight: "32 - 45 Kilograms",
    Height: "60 - 70 Centimeters",
    LifeSpan: "10 - 16 Years",
    NumberLeft: "8,000 (5,500 females)",
    EndangeredSince: "1970",
    Region: "the Gulf of Mexico",
    img: "image-01.jpg",
    id: "004",
  },
  {
    Name: "Steller Sea Lion (Eumetopias jubatus)",
    EndangeredType: "Endangered",
    Weight: "200-300 kilograms",
    Height: "2.1-2.4 meters",
    LifeSpan: "Upto 20 years",
    NumberLeft: "45,000",
    EndangeredSince: "1990",
    Region:
      "Coastal Waters in the Northern Pacific Ocean, from Japan to Central California",
    img: "image-01.jpg",
    id: "005",
  },
  {
    Name: "Hammerhead Shark (Sphyrna mokarran)",
    EndangeredType: "Endangered",
    Weight: "230 kilograms",
    Height: "4 meters",
    LifeSpan: "Around 20 to 30 years",
    NumberLeft: "200",
    EndangeredSince: "2011",
    Region: "Western Atlantic Ocean",
    img: "image-01.jpg",
    id: "006",
  },
];
